import { test, expect } from '@playwright/test'

test('flagship demo persists generations and cells, updates live SQL and edits users', async ({ page }) => {
	const errors: string[] = []
	page.on('pageerror', error => errors.push(error.message))
	await page.goto('/')
	await expect(page.getByRole('button', {name:'Step',exact:true})).toBeVisible()
	await expect(page.getByText('SQLite connected', {exact:true})).toBeVisible()
	await page.getByRole('button',{name:'Step',exact:true}).click()
	await expect(page.locator('.board-heading')).toContainText('GENERATION 1')
	const before = await page.locator('.board-heading').textContent()
	await page.reload()
	await expect(page.locator('.board-heading')).toHaveText(before ?? '')
	await page.getByRole('button',{name:'SQL playground',exact:true}).click()
	await page.getByRole('button',{name:'Generation',exact:true}).click()
	await expect(page.locator('.sql-section:visible .data-table tbody')).toContainText('1')
	await page.getByRole('button',{name:'Game of Life',exact:true}).click()
	await page.getByRole('button',{name:'Step',exact:true}).click()
	await expect(page.locator('.board-heading')).toContainText('GENERATION 2')
	await page.getByRole('button',{name:'SQL playground',exact:true}).click()
	await expect(page.locator('.sql-section:visible .data-table tbody tr td').first()).toHaveText('2')
	await page.getByRole('button',{name:'Tables',exact:true}).click()
	await page.getByLabel('Name',{exact:true}).fill('Grace Hopper')
	await page.getByLabel('Email',{exact:true}).fill('grace@example.test')
	await page.getByRole('button',{name:'Insert user'}).click()
	await expect(page.locator('.users-table')).toContainText('grace@example.test')
	await page.getByRole('button',{name:'Delete Grace Hopper'}).click()
	await expect(page.locator('.users-table')).not.toContainText('grace@example.test')
	await page.getByRole('button',{name:'Subscriptions',exact:true}).click()
	await expect(page.locator('.subscription-row')).not.toHaveCount(0)
	await expect(page.locator('.change-stream tbody tr')).not.toHaveCount(0)
	const download = page.waitForEvent('download')
	await page.getByRole('button',{name:'Export database'}).click()
	expect((await download).suggestedFilename()).toBe('sqlite-sync.db')
	expect(errors).toEqual([])
	await page.getByRole('button',{name:'Game of Life',exact:true}).click()
	await page.screenshot({path:'test-results/demo-desktop.png',fullPage:true})
})

test('mobile layout is usable with reduced motion', async ({ page }) => {
	await page.setViewportSize({width:390,height:844})
	await page.emulateMedia({reducedMotion:'reduce'})
	await page.goto('/')
	await expect(page.getByRole('button',{name:'Step',exact:true})).toBeVisible()
	expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
	await page.screenshot({path:'test-results/demo-mobile.png',fullPage:true})
})
